### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by airon90** [bsudekum/navigation#1]
Hi, how can I translate the navigator into Italian and Esperanto? Thank you!

**Comment by bsudekum** [comment]
This project is leveraging the mapbox directions api which does not have directions in other languages.

**Comment by airon90** [comment]
What about the content of this div? https://github.com/rsudekum/navigation/blob/gh-pages/index.html#L23

**Comment by bsudekum** [comment]
@Airon90 Sure, all of this text can be translated, but all directions will be in english.
